function [] = plot_decision_boundry_multi(X,theta)

z = @(x,y) (...
            (theta(1))...
            +(x.*theta(2))...
            +(y.*theta(3))...
            +(x.^2).*theta(4)...
            +(x.*y.*theta(5))...
            +(y.^2).*theta(6)...
            +(x.^3).*theta(7)...
            +(y.*(x.^2)*theta(8))...
            +(x.*(y.^2)*theta(9))...
            +((y.^3).*theta(10))...
            +((x.^4).*theta(11))...
            +(y.*(x.^3).*theta(12))...
            +((x.^2).*(y.^2).*theta(13))...
            +(x.*(y.^3).*theta(14))...
            +((y.^4).*theta(15))...
            +((x.^5).*theta(16))...
            +((x.^4).*y.*theta(17))...
            +((x.^3).*(y.^2).*theta(18))...
            +((x.^2).*(y.^3).*theta(19))...
            +(x.*(y.^4).*theta(20))...
            +((y.^5).*theta(21))...
            +((x.^6).*theta(22))...
            +((x.^5).*y.*theta(23))...
            +((x.^4).*(y.^2).*theta(24))...
            +((x.^3).*(y.^3).*theta(25))...
            +((x.^2).*(y.^4).*theta(26))...
            +(x.*(y.^5).*theta(27))...
            +((y.^6).*theta(28))...
            );
            
        
fimplicit(z,'-b','LineWidth',2);

end

